# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from strategies.api.grpc import strategies_pb2 as strategies_dot_api_dot_grpc_dot_strategies__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in strategies/api/grpc/strategies_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStrategies = channel.unary_unary(
                '/strategies.api.grc.StrategyService/GetStrategies',
                request_serializer=strategies_dot_api_dot_grpc_dot_strategies__pb2.Empty.SerializeToString,
                response_deserializer=strategies_dot_api_dot_grpc_dot_strategies__pb2.StrategiesResponse.FromString,
                _registered_method=True)
        self.GetSymbolsForStrategyAndInterval = channel.unary_unary(
                '/strategies.api.grc.StrategyService/GetSymbolsForStrategyAndInterval',
                request_serializer=strategies_dot_api_dot_grpc_dot_strategies__pb2.StrategyAndIntervalRequest.SerializeToString,
                response_deserializer=strategies_dot_api_dot_grpc_dot_strategies__pb2.SymbolsResponse.FromString,
                _registered_method=True)


class StrategyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSymbolsForStrategyAndInterval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategies,
                    request_deserializer=strategies_dot_api_dot_grpc_dot_strategies__pb2.Empty.FromString,
                    response_serializer=strategies_dot_api_dot_grpc_dot_strategies__pb2.StrategiesResponse.SerializeToString,
            ),
            'GetSymbolsForStrategyAndInterval': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSymbolsForStrategyAndInterval,
                    request_deserializer=strategies_dot_api_dot_grpc_dot_strategies__pb2.StrategyAndIntervalRequest.FromString,
                    response_serializer=strategies_dot_api_dot_grpc_dot_strategies__pb2.SymbolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'strategies.api.grc.StrategyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('strategies.api.grc.StrategyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategies.api.grc.StrategyService/GetStrategies',
            strategies_dot_api_dot_grpc_dot_strategies__pb2.Empty.SerializeToString,
            strategies_dot_api_dot_grpc_dot_strategies__pb2.StrategiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSymbolsForStrategyAndInterval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategies.api.grc.StrategyService/GetSymbolsForStrategyAndInterval',
            strategies_dot_api_dot_grpc_dot_strategies__pb2.StrategyAndIntervalRequest.SerializeToString,
            strategies_dot_api_dot_grpc_dot_strategies__pb2.SymbolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
