# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: strategies/api/grpc/strategies.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'strategies/api/grpc/strategies.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$strategies/api/grpc/strategies.proto\x12\x12strategies.api.grc\"\x07\n\x05\x45mpty\"@\n\x1aStrategyAndIntervalRequest\x12\x10\n\x08strategy\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\"9\n\x12StrategiesResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nstrategies\x18\x02 \x03(\t\"3\n\x0fSymbolsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07symbols\x18\x02 \x03(\t2\xde\x01\n\x0fStrategyService\x12R\n\rGetStrategies\x12\x19.strategies.api.grc.Empty\x1a&.strategies.api.grc.StrategiesResponse\x12w\n GetSymbolsForStrategyAndInterval\x12..strategies.api.grc.StrategyAndIntervalRequest\x1a#.strategies.api.grc.SymbolsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strategies.api.grpc.strategies_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=60
  _globals['_EMPTY']._serialized_end=67
  _globals['_STRATEGYANDINTERVALREQUEST']._serialized_start=69
  _globals['_STRATEGYANDINTERVALREQUEST']._serialized_end=133
  _globals['_STRATEGIESRESPONSE']._serialized_start=135
  _globals['_STRATEGIESRESPONSE']._serialized_end=192
  _globals['_SYMBOLSRESPONSE']._serialized_start=194
  _globals['_SYMBOLSRESPONSE']._serialized_end=245
  _globals['_STRATEGYSERVICE']._serialized_start=248
  _globals['_STRATEGYSERVICE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
